{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Section 6 - Intermediate and advanced topics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.1 Set project units"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "public void S6_1_setUnits()\n",
    "{\n",
    "\tDocument doc = this.Document;\n",
    "\tUnits units = doc.GetUnits();\n",
    "\t\n",
    "\tFormatOptions foLength = units.GetFormatOptions(UnitType.UT_Length);\n",
    "\tfoLength.DisplayUnits = DisplayUnitType.DUT_MILLIMETERS;\n",
    "\tfoLength.UnitSymbol = UnitSymbolType.UST_MM;\n",
    "\tfoLength.Accuracy = 10;\n",
    "\t\n",
    "\tFormatOptions foVolume = units.GetFormatOptions(UnitType.UT_Volume);\n",
    "\tfoVolume.DisplayUnits = DisplayUnitType.DUT_CUBIC_METERS;\n",
    "\tfoVolume.UnitSymbol = UnitSymbolType.UST_NONE;\n",
    "\t\n",
    "\tunits.SetFormatOptions(UnitType.UT_Length, foLength);\n",
    "\tunits.SetFormatOptions(UnitType.UT_Volume, foVolume);\n",
    "\t\n",
    "\tusing(Transaction t = new Transaction(doc, \"set units\"))\n",
    "\t{\n",
    "\t\tt.Start();\n",
    "\t\tdoc.SetUnits(units);\n",
    "\t\tt.Commit();\n",
    "\t}\n",
    "\t\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.2 Selection filters"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic void S6_2_selectElementWithFilter()\n",
    "\t\t{\n",
    "\t\t\tUIDocument uidoc = this.ActiveUIDocument;\n",
    "\t\t\tDocument doc = uidoc.Document;\n",
    "\t\t\t\n",
    "\t\t\tReference myRefWall = uidoc.Selection.PickObject(ObjectType.Element, new GenericSelectionFilter(\"Walls\"), \"Select a wall\");\n",
    "\t\t\tReference myRefFloor = uidoc.Selection.PickObject(ObjectType.Element, new GenericSelectionFilter(\"Floors\"), \"Select a floor\");\n",
    "\t\t\t\n",
    "//\t\t\tElement e = doc.GetElement(myRef);\n",
    "//\t\t\t\n",
    "//\t\t\tstring designOptionName = \"<none>\";\n",
    "//\t\t\tif (e.DesignOption != null)\n",
    "//\t\t\t{\n",
    "//\t\t\t\tdesignOptionName = e.DesignOption.Name;\n",
    "//\t\t\t}\n",
    "//\t\t\t\n",
    "//\t\t\tTaskDialog.Show(\"Element Info\",e.Name + Environment.NewLine + e.Id + \"\\n\" + designOptionName);\n",
    "\n",
    "\t\t}\n",
    "\t\t\n",
    "\t\tpublic class GenericSelectionFilter : ISelectionFilter\n",
    "\t\t{\n",
    "\t\t\tstatic string CategoryName = \"\";\n",
    "\t\t\t\n",
    "\t\t\tpublic GenericSelectionFilter(string name)\n",
    "\t\t\t{\n",
    "\t\t\t\tCategoryName = name;\n",
    "\t\t\t}\n",
    "\t\t\t\n",
    "\t\t\tpublic bool AllowElement(Element e)\n",
    "\t\t\t{\n",
    "\t\t\t\tif (e.Category.Name == CategoryName)\n",
    "\t\t\t\t\treturn true;\n",
    "\t\t\t\t\n",
    "\t\t\t\treturn false;\n",
    "\t\t\t}\n",
    "\t\t\tpublic bool AllowReference(Reference r, XYZ point)\n",
    "\t\t\t{\n",
    "\t\t\t\treturn true;\n",
    "\t\t\t}\n",
    "\t\t}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.3 Events"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic void S6_3_registerSaveEvent()\n",
    "\t\t{\n",
    "\t\t\tDocument doc = this.ActiveUIDocument.Document;\n",
    "\t\t\tdoc.DocumentSaving += new EventHandler<DocumentSavingEventArgs>(myDocumentSaving);\n",
    "\t\t}\n",
    "\t\t\n",
    "\t\tprivate void myDocumentSaving(object sender, DocumentSavingEventArgs args)\n",
    "\t\t{\n",
    "\t\t\tDocument doc = sender as Document;\n",
    "\t\t\tstring user = doc.Application.Username;\n",
    "\t\t\tstring filename = doc.PathName;\n",
    "\t\t\tstring filenameShort = Path.GetFileNameWithoutExtension(filename);\n",
    "\t\t\tstring tempFolder = Path.GetTempPath();\n",
    "\t\t\tstring outputFile = Path.Combine(tempFolder,filenameShort + \".txt\");\n",
    "\t\t\tusing (StreamWriter sw = new StreamWriter(outputFile,true))\n",
    "\t\t\t{\n",
    "\t\t\t\tsw.WriteLine(DateTime.Now + \": \" + user);\n",
    "\t\t\t}\n",
    "\t\t}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.4 Ribbon UI - Tabs, panels and buttons"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "https://www.dotnetperls.com/uri"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "https://docs.microsoft.com/en-us/dotnet/api/system.uri?redirectedfrom=MSDN&view=net-5.0"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\n",
    "<RevitAddIns>\n",
    "  <AddIn Type=\"Application\">\n",
    "    <Name>ribbonUI</Name>\n",
    "    <Assembly>C:\\Users\\harry_000\\Documents\\repos\\BoostYourBIM\\BoostYourBIM\\bin\\Debug\\BoostYourBIM.dll</Assembly>\n",
    "    <AddInId>b31111f3-772b-4207-8b1a-891689513353</AddInId>\n",
    "    <FullClassName>BoostYourBIM.ribbonUI</FullClassName>\n",
    "    <VendorId>BYBM</VendorId>\n",
    "  </AddIn>\n",
    "</RevitAddIns>"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "using Autodesk.Revit.DB;\n",
    "using Autodesk.Revit.UI;\n",
    "using System;\n",
    "using System.Collections.Generic;\n",
    "using System.IO;\n",
    "using System.Linq;\n",
    "using System.Text;\n",
    "using System.Threading.Tasks;\n",
    "using System.Windows.Media.Imaging;\n",
    "\n",
    "namespace BoostYourBIM\n",
    "{\n",
    "    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n",
    "    public class One : IExternalCommand\n",
    "    {\n",
    "        static AddInId appId = new AddInId(new Guid(\"B31111F3-772B-4207-8C1A-891689513353\"));\n",
    "        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)\n",
    "        {\n",
    "            Autodesk.Revit.ApplicationServices.Application app = commandData.Application.Application;\n",
    "            Document doc = commandData.Application.ActiveUIDocument.Document;\n",
    "            UIDocument uidoc = new UIDocument(doc);\n",
    "            TaskDialog.Show(\"One\", \"One\");\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }\n",
    "\n",
    "    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n",
    "    public class Two : IExternalCommand\n",
    "    {\n",
    "        static AddInId appId = new AddInId(new Guid(\"A31111F3-772B-4207-8C1A-891689513353\"));\n",
    "        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)\n",
    "        {\n",
    "            Autodesk.Revit.ApplicationServices.Application app = commandData.Application.Application;\n",
    "            Document doc = commandData.Application.ActiveUIDocument.Document;\n",
    "            UIDocument uidoc = new UIDocument(doc);\n",
    "            TaskDialog.Show(\"Two\", \"Two\");\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }\n",
    "\n",
    "    class ribbonUI : IExternalApplication\n",
    "    {\n",
    "        // references to WindowsBase and System.Xaml are needed\n",
    "\n",
    "        public Autodesk.Revit.UI.Result OnStartup(UIControlledApplication application)\n",
    "        {\n",
    "            string folderPath = @\"C:\\Users\\harry_000\\Documents\\repos\\BoostYourBIM\\BoostYourBIM\\bin\\Debug\";\n",
    "            string dll = Path.Combine(folderPath, \"BoostYourBIM.dll\");\n",
    "\n",
    "            string myRibbon = \"Boost Your BIM\";\n",
    "            application.CreateRibbonTab(myRibbon);\n",
    "\n",
    "            RibbonPanel panelA = application.CreateRibbonPanel(myRibbon, \"A\");\n",
    "            RibbonPanel panelB = application.CreateRibbonPanel(myRibbon, \"B\");\n",
    "\n",
    "            // Standard buttons\n",
    "\n",
    "            PushButton btnOne = (PushButton)panelA.AddItem(new PushButtonData(\"One\", \"One\", dll, \"BoostYourBIM.One\"));\n",
    "            // need reference to PresentationCore to get access to the System.Windows.Media.Imaging namespace which includes BitmapImage\n",
    "            btnOne.LargeImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"image32.png\"), UriKind.Absolute));\n",
    "            btnOne.Image = new BitmapImage(new Uri(Path.Combine(folderPath, \"image16.png\"), UriKind.Absolute));\n",
    "            btnOne.ToolTipImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"thumbsUp.JPG\"), UriKind.Absolute));\n",
    "            btnOne.ToolTip = \"Button One Tool Tip\";\n",
    "            btnOne.LongDescription = \"This command is great. It is really great. Really really wonderful!\";\n",
    "\n",
    "            PushButton btnTwo = (PushButton)panelA.AddItem(new PushButtonData(\"Two\", \"Two\", dll, \"BoostYourBIM.Two\"));\n",
    "            btnTwo.LargeImage = new BitmapImage(new Uri(\"http://boostyourbim.files.wordpress.com/2013/08/note.png\"));\n",
    "            btnTwo.Image = new BitmapImage(new Uri(\"http://boostyourbim.files.wordpress.com/2013/08/notesmall.png\"));\n",
    "\n",
    "            // Pull down button\n",
    "\n",
    "            PulldownButtonData pullDownData = new PulldownButtonData(\"My PullDown\", \"My PullDown\");\n",
    "\n",
    "            pullDownData.Image = new BitmapImage(new Uri(Path.Combine(folderPath, \"image16.png\"), UriKind.Absolute));\n",
    "            pullDownData.LargeImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"image32.png\"), UriKind.Absolute));\n",
    "            PulldownButton pullDownButton = panelB.AddItem(pullDownData) as PulldownButton;\n",
    "\n",
    "            PushButton btnTagAllByCategory = pullDownButton.AddPushButton(new PushButtonData(\"One\", \"Item One\", dll, \"BoostYourBIM.One\"));\n",
    "            PushButton btnTagAllBySelection = pullDownButton.AddPushButton(new PushButtonData(\"Two\", \"Item Two\", dll, \"BoostYourBIM.Two\"));\n",
    "            PushButton btnTagAllByFamily = pullDownButton.AddPushButton(new PushButtonData(\"Three\", \"Item Three\", dll, \"BoostYourBIM.Three\"));\n",
    "\n",
    "            // Stacked list\n",
    "\n",
    "            PushButtonData dataHelp = new PushButtonData(\"Help\", \"Help\", dll, \"BoostYourBIM.help\");\n",
    "            PushButtonData dataAbout = new PushButtonData(\"About\", \"About\", dll, \"BoostYourBIM.about\");\n",
    "            PushButtonData dataFeedback = new PushButtonData(\"Feedback\", \"Feedback\", dll, \"BoostYourBIM.feedback\");\n",
    "\n",
    "            IList<RibbonItem> stackedList = panelB.AddStackedItems(dataHelp, dataAbout, dataFeedback);\n",
    "\n",
    "            PushButton btnHelp = (PushButton)stackedList[0];\n",
    "            btnHelp.LargeImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"image32.png\"), UriKind.Absolute));\n",
    "            btnHelp.Image = new BitmapImage(new Uri(Path.Combine(folderPath, \"image16.png\"), UriKind.Absolute));\n",
    "            btnHelp.ToolTip = \"Click for our web-based help\";\n",
    "\n",
    "            PushButton btnAbout = (PushButton)stackedList[1];\n",
    "            btnAbout.LargeImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"image32.png\"), UriKind.Absolute));\n",
    "            btnAbout.Image = new BitmapImage(new Uri(Path.Combine(folderPath, \"image16.png\"), UriKind.Absolute));\n",
    "            btnAbout.ToolTip = \"About these tools\";\n",
    "\n",
    "            PushButton btnFeedback = (PushButton)stackedList[2];\n",
    "            btnFeedback.LargeImage = new BitmapImage(new Uri(Path.Combine(folderPath, \"image32.png\"), UriKind.Absolute));\n",
    "            btnFeedback.Image = new BitmapImage(new Uri(Path.Combine(folderPath, \"image16.png\"), UriKind.Absolute));\n",
    "            btnFeedback.ToolTip = \"Click to email us with your feedback\";\n",
    "\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "\n",
    "        public Result OnShutdown(UIControlledApplication application)\n",
    "        {\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "// The question was asked \"In this ribbon example you've got a button that performs function \"one\" and a button for function \"two\". Is it possible to create a third button that runs the two functions consecutively?\"\n",
    "\n",
    "// The code below shows a solution that involves moving the implementation of each command out of the body of the IExternalCommand class and into a method of an \"implementation\" class\n",
    "\n",
    "    public static class implementation\n",
    "    {\n",
    "        public static void a()\n",
    "        {\n",
    "            TaskDialog.Show(\"a\", \"a\");\n",
    "        }\n",
    "\n",
    "        public static void b()\n",
    "        {\n",
    "            TaskDialog.Show(\"b\", \"b\");\n",
    "        }\n",
    "    }\n",
    "\n",
    "    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n",
    "    public class a : IExternalCommand\n",
    "    {\n",
    "        static AddInId appId = new AddInId(new Guid(\"B37a12A3-721A-4207-8C1A-891189513353\"));\n",
    "        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)\n",
    "        {\n",
    "            implementation.a();\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }\n",
    "\n",
    "    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n",
    "    public class b : IExternalCommand\n",
    "    {\n",
    "        static AddInId appId = new AddInId(new Guid(\"B37b12A3-721A-4207-8C1A-891189513353\"));\n",
    "        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)\n",
    "        {\n",
    "            implementation.b();\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }\n",
    "\n",
    "    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n",
    "    public class c : IExternalCommand\n",
    "    {\n",
    "        static AddInId appId = new AddInId(new Guid(\"B37b12A3-721A-4107-8C1A-891189513353\"));\n",
    "        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)\n",
    "        {\n",
    "            implementation.a();\n",
    "            implementation.b();\n",
    "            return Result.Succeeded;\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "string myRibbon = \"Boost Your BIM\";\n",
    "application.CreateRibbonTab(myRibbon);\n",
    "\n",
    "RibbonPanel panelA = application.CreateRibbonPanel(myRibbon, \"A\");\n",
    "\n",
    "PulldownButtonData pullDownData1 = new PulldownButtonData(\"My PullDown1\", \"My PullDown1\");\n",
    "PulldownButtonData pullDownData2 = new PulldownButtonData(\"My PullDown2\", \"My PullDown2\");\n",
    "PulldownButtonData pullDownData3 = new PulldownButtonData(\"My PullDown3\", \"My PullDown3\");\n",
    "IList<RibbonItem> stackedList = panelA.AddStackedItems(pullDownData1, pullDownData2, pullDownData3);\n",
    "\n",
    "// for brevity, this example reuses these 3 buttons in each dropdown\n",
    "// in real life you would create new PushButtonData elements for each button in each dropdown\n",
    "PushButtonData pbdataOne = new PushButtonData(\"1\", \"Item 1\", dll, \"BoostYourBIM.One\");\n",
    "PushButtonData pbdataTwo = new PushButtonData(\"2\", \"Item 2\", dll, \"BoostYourBIM.Two\");\n",
    "PushButtonData pbdataThree = new PushButtonData(\"3\", \"Item 3\", dll, \"BoostYourBIM.Three\");\n",
    "\n",
    "PulldownButton pullDownButton1 = (PulldownButton)stackedList[0];\n",
    "PushButton mPushButton1 = pullDownButton1.AddPushButton(pbdataOne);\n",
    "PushButton mPushButton2 = pullDownButton1.AddPushButton(pbdataTwo);\n",
    "PushButton mPushButton3 = pullDownButton1.AddPushButton(pbdataThree);\n",
    "\n",
    "PulldownButton pullDownButton2 = (PulldownButton)stackedList[1];\n",
    "PushButton mPushButton21 = pullDownButton2.AddPushButton(pbdataOne);\n",
    "PushButton mPushButton22 = pullDownButton2.AddPushButton(pbdataTwo);\n",
    "PushButton mPushButton23 = pullDownButton2.AddPushButton(pbdataThree);\n",
    "\n",
    "PulldownButton pullDownButton3 = (PulldownButton)stackedList[2];\n",
    "PushButton mPushButton31 = pullDownButton3.AddPushButton(pbdataOne);\n",
    "PushButton mPushButton32 = pullDownButton3.AddPushButton(pbdataTwo);\n",
    "PushButton mPushButton33 = pullDownButton3.AddPushButton(pbdataThree);"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.5 Write comments to the journal file"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic void location()\n",
    "\t\t{\n",
    "\t\t\tDocument doc = this.ActiveUIDocument.Document;\n",
    "\t\t\tUIDocument uidoc = this.ActiveUIDocument;\n",
    "\t\t\tElement e = doc.GetElement(uidoc.Selection.PickObject(ObjectType.Element));\n",
    "\t\t\t\n",
    "\t\t\tLocation location = e.Location;\n",
    "\t\t\t\n",
    "\t\t\tif (location is LocationCurve)\n",
    "\t\t\t{\n",
    "\t\t\t\tLocationCurve lc = location as LocationCurve;\n",
    "\t\t\t\tCurve c = lc.Curve;\n",
    "\t\t\t\tXYZ end0 = c.GetEndPoint(0);\n",
    "\t\t\t\tXYZ end1 = c.GetEndPoint(1);\n",
    "\t\t\t\t//TaskDialog.Show(\"Curve endpoints\", end0.ToString() + Environment.NewLine + end1.ToString());\\\n",
    "\t\t\t\tdoc.Application.WriteJournalComment(\"LocationMacro: \" + end0.ToString() + \" - \" + end1.ToString(), false);\n",
    "\t\t\t\tdoc.Application.WriteJournalComment(\"LocationMacro: \" + c.ToString(), false);\n",
    "\t\t\t\tif (c is Line)\n",
    "\t\t\t\t{\n",
    "\t\t\t\t\tLine line = c as Line;\n",
    "\t\t\t\t\t//TaskDialog.Show(\"Direction\", line.Direction.ToString());\n",
    "\t\t\t\t}\n",
    "\t\t\t\telse\n",
    "\t\t\t\t{\n",
    "\t\t\t\t\tTransform t = c.ComputeDerivatives(0.5, true);\n",
    "\t\t\t\t\tXYZ tangent = t.BasisX;\n",
    "\t\t\t\t\tXYZ tangentNormal = tangent.Normalize();\n",
    "\t\t\t\t\t//TaskDialog.Show(\"Direction\", tangent.ToString() + Environment.NewLine + tangentNormal.ToString());\n",
    "\t\t\t\t}\n",
    "\t\t\t\t\n",
    "\t\t\t}\n",
    "\t\t\telse\n",
    "\t\t\t{\n",
    "\t\t\t\tLocationPoint lp = location as LocationPoint;\n",
    "\t\t\t\tXYZ point = lp.Point;\n",
    "\t\t\t\tTaskDialog.Show(\"Point\",point.ToString());\n",
    "\t\t\t}\n",
    "\t\t}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.6 Extensible storage"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic void ExtensibleStorage_SetData()\n",
    "\t\t{\t\t\t\n",
    "\t\t\tstring schemaName = \"PurchasingInfo\";\n",
    "\t\t\t\n",
    "\t\t\t// check to see if schema exists\n",
    "\t\t\tSchema mySchema = Schema.ListSchemas().FirstOrDefault(q => q.SchemaName == schemaName);\n",
    "\t\t\t\n",
    "\t\t\t// if schema doesn't exist, create it\n",
    "\t\t\tif (mySchema == null)\n",
    "\t\t\t{\n",
    "\t\t\t\tGuid myGuid = new Guid(\"1f5f9bf4-8760-457f-80e6-348740730775\");\n",
    "\t\t\t\tSchemaBuilder sb = new SchemaBuilder(myGuid);\n",
    "\t\t\t\tsb.SetSchemaName(schemaName);\n",
    "\t\t\t\t\n",
    "\t\t\t\t// add fields (properties) to schema, defining the name and data type for each field\n",
    "\t\t\t\tFieldBuilder fbCost = sb.AddSimpleField(\"Cost\",typeof(Int32));\n",
    "\t\t\t\tFieldBuilder fbShippingWeight = sb.AddSimpleField(\"ShippingWeight\",typeof(double));\n",
    "\t\t\t\t// set the Unit Type of the Shipping Weight\n",
    "\t\t\t\tfbShippingWeight.SetUnitType(UnitType.UT_Mass);\n",
    "\t\t\t\t\n",
    "\t\t\t\t// conclude the creation of the schema\n",
    "\t\t\t\tmySchema = sb.Finish();\n",
    "\t\t\t}\n",
    "\t\t\t\n",
    "\t\t\t// create entity of schema (like an instance of a class)\n",
    "\t\t\tEntity myEntity = new Entity(mySchema);\n",
    "\t\t\t\n",
    "\t\t\t// get the fields from the schema\n",
    "\t\t\tField myCostField = mySchema.GetField(\"Cost\");\n",
    "\t\t\tField myShipWeightField = mySchema.GetField(\"ShippingWeight\");\n",
    "\t\t\t\n",
    "\t\t\t// set value for this entity for each field\n",
    "\t\t\tmyEntity.Set<Int32>(myCostField, 125);\n",
    "\t\t\tmyEntity.Set<double>(myShipWeightField, 1, DisplayUnitType.DUT_KILOGRAMS_MASS);\n",
    "\t\t\n",
    "\t\t\t// prompt user to select an element\n",
    "\t\t\tDocument doc = this.ActiveUIDocument.Document;\n",
    "\t\t\tUIDocument uidoc = this.ActiveUIDocument;\n",
    "\t\t\tElement element = doc.GetElement(uidoc.Selection.PickObject(ObjectType.Element));\n",
    "\t\t\t\n",
    "\t\t\t// store the data in the element\n",
    "\t\t\tusing (Transaction t = new Transaction(doc,\"Store Data\"))\n",
    "\t\t\t{\n",
    "\t\t\t\tt.Start();\n",
    "\t\t\t\telement.SetEntity(myEntity);\n",
    "\t\t\t\tt.Commit();\n",
    "\t\t\t}\n",
    "\t\t}\n",
    "\t\t\n",
    "\t\t// add a using statement for the Autodesk.Revit.DB.ExtensibleStorage namespace\n",
    "\t\tpublic void ExtensibleStorage_GetData()\n",
    "\t\t{\n",
    "\t\t\t// get the schema with ListSchemas\n",
    "\t\t\tstring schemaName = \"PurchasingInfo\";\n",
    "\t\t\tSchema mySchema = Schema.ListSchemas().FirstOrDefault(q => q.SchemaName == schemaName);\n",
    "\t\t\t\n",
    "\t\t\t// diagnostics in the event that the desired schema was not found\n",
    "\t\t\tif (mySchema == null)\n",
    "\t\t\t{\n",
    "\t\t\t\tstring allSchema = \"\";\n",
    "\t\t\t\tforeach (Schema s in Schema.ListSchemas())\n",
    "\t\t\t\t{\n",
    "\t\t\t\t\tallSchema += s.SchemaName + Environment.NewLine;\n",
    "\t\t\t\t}\n",
    "\t\t\t\tTaskDialog.Show(\"error\",\"Schema not found \" + schemaName);\n",
    "\t\t\t\tTaskDialog.Show(\"All Schemas\",allSchema);\n",
    "\t\t\t\treturn;\n",
    "\t\t\t}\n",
    "\t\t\t\n",
    "\t\t\t// get the fields from the schema\n",
    "\t\t\tField myCostField = mySchema.GetField(\"Cost\");\n",
    "\t\t\tField myShipWeightField = mySchema.GetField(\"ShippingWeight\");\n",
    "\t\t\t\n",
    "\t\t\t// prompt user to select an element\n",
    "\t\t\tDocument doc = this.ActiveUIDocument.Document;\n",
    "\t\t\tUIDocument uidoc = this.ActiveUIDocument;\n",
    "\t\t\tElement element = doc.GetElement(uidoc.Selection.PickObject(ObjectType.Element));\n",
    "\t\t\t\n",
    "\t\t\t// get the entity from the element\n",
    "\t\t\tEntity myEntity = element.GetEntity(mySchema);\n",
    "\t\t\t\n",
    "\t\t\t// get the data from the entity\n",
    "\t\t\tInt32 cost = myEntity.Get<Int32>(\"Cost\");\n",
    "\t\t\tdouble weight = myEntity.Get<double>(myShipWeightField, DisplayUnitType.DUT_POUNDS_MASS);\n",
    "\t\t\t\n",
    "\t\t\tTaskDialog.Show(schemaName,cost + Environment.NewLine + weight);\n",
    "\t\t}\n",
    "\t\t"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.7 Reference intersector"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic void referenceIntersector()\n",
    "\t\t{\n",
    "\t\t\tDocument doc = this.ActiveUIDocument.Document;\n",
    "\t\t\tView3D view3d = doc.ActiveView as View3D;\n",
    "\t\t\tif (view3d == null)\n",
    "\t\t\t{\n",
    "\t\t\t\tTaskDialog.Show(\"Error\",\"Active view must be a 3d view\");\n",
    "\t\t\t\treturn;\n",
    "\t\t\t}\n",
    "\t\t\tReferenceIntersector ri = new ReferenceIntersector(view3d);\n",
    "\t\t\tIList<ReferenceWithContext> refWithContextList = ri.Find(XYZ.Zero,XYZ.BasisY);\n",
    "\t\t\tstring data = \"\";\n",
    "\t\t\tforeach (ReferenceWithContext rwc in refWithContextList)\n",
    "\t\t\t{\n",
    "\t\t\t\tReference r = rwc.GetReference();\n",
    "\t\t\t\tdouble d = rwc.Proximity;\n",
    "\t\t\t\tElement e = doc.GetElement(r);\n",
    "\t\t\t\t\n",
    "\t\t\t\tGeometryObject o = e.GetGeometryObjectFromReference(r);\n",
    "\t\t\t\tstring oType = o.GetType().ToString();\n",
    "\t\t\t\tdata += oType + \" - \" + e.Name + \" - \" + d + Environment.NewLine;\n",
    "\t\t\t}\n",
    "\t\t\tTaskDialog.Show(\"elements hit\",data);\n",
    "\t\t}\n",
    "\t\t"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6.8 Dynamic model update"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "\t\tpublic class TextTypeUpdater : IUpdater\n",
    "\t\t{\n",
    "\t\t    static AddInId m_appId;\n",
    "\t\t    static UpdaterId m_updaterId;\n",
    "\t\t    // constructor takes the AddInId for the add-in associated with this updater\n",
    "\t\t    public TextTypeUpdater(AddInId id)\n",
    "\t\t    {\n",
    "\t\t        m_appId = id;\n",
    "\t\t        // every Updater must have a unique ID\n",
    "\t\t        m_updaterId = new UpdaterId(m_appId, new Guid(\"FBFBF6B2-4C06-42d4-97C1-D1B4EB593EFF\"));\n",
    "\t\t    }\n",
    "\t\t    public void Execute(UpdaterData data)\n",
    "\t\t    {\n",
    "\t\t        Document doc = data.GetDocument();\n",
    "\t\t\n",
    "\t\t        // loop through the list of added elements\n",
    "\t\t        foreach (ElementId addedElemId in data.GetAddedElementIds())\n",
    "\t\t        {\n",
    "\t\t        \tTextNoteType textNoteType = doc.GetElement(addedElemId) as TextNoteType;\n",
    "\t            \tstring name = textNoteType.Name;\n",
    "\t            \tdoc.Delete(addedElemId);\n",
    "\t            \tTaskDialog.Show(\"New Element Deleted!\", \"Text type '\" + name + \"' has been deleted. Please use existing text types in the template.\");\n",
    "\t\t        }\n",
    "\t\t    }\n",
    "\t\t    public string GetAdditionalInformation(){return \"Text note type check\";}\n",
    "\t\t    public ChangePriority GetChangePriority(){return ChangePriority.FloorsRoofsStructuralWalls;}\n",
    "\t\t    public UpdaterId GetUpdaterId(){return m_updaterId;}\n",
    "\t\t    public string GetUpdaterName(){return \"Text note type\";}\n",
    "\t\t}\n",
    "\t\t\n",
    "\t\tpublic void RegisterUpdater()\n",
    "\t\t{\n",
    "\t\t    TextTypeUpdater updater = new TextTypeUpdater(this.Application.ActiveAddInId);\n",
    "\t\t    UpdaterRegistry.RegisterUpdater(updater);\n",
    "\t\t\n",
    "\t\t    // Trigger will occur only for TextNoteType elements\n",
    "\t\t    ElementClassFilter textNoteTypeFilter = new ElementClassFilter(typeof(TextNoteType));\n",
    "\t\t\n",
    "\t\t    // GetChangeTypeElementAddition specifies that the triggger will occur when elements are added\n",
    "\t\t    // Other options are GetChangeTypeAny, GetChangeTypeElementDeletion, GetChangeTypeGeometry, GetChangeTypeParameter\n",
    "\t\t    UpdaterRegistry.AddTrigger(updater.GetUpdaterId(), textNoteTypeFilter, Element.GetChangeTypeElementAddition());\n",
    "\t\t}\n",
    "\t\t\n",
    "\t\tpublic void UnregisterUpdater()\n",
    "\t\t{\n",
    "\t\t    TextTypeUpdater updater = new TextTypeUpdater(this.Application.ActiveAddInId);\n",
    "\t\t    UpdaterRegistry.UnregisterUpdater(updater.GetUpdaterId());\n",
    "\t\t}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
